### ISSUE TITLE
archbuild: local repositories not bound when chroot is updated

### ISSUE THREAD

**Issue by jrouleau** [archlinux/devtools#14]
When pacman is run to update the chroot, local repositories are not bound causing pacman to fail

https://github.com/archlinux/devtools/blob/d8d2e23247a1aab5e269ff0e388e378ec9d462eb/archbuild.in#L79-L83

```
error: failed retrieving file 'custom.db' from disk : Couldn't open file [...]
error: failed to update custom (download library error)
 core is up to date
 extra is up to date
 community is up to date
error: failed to synchronize all databases
==> ERROR: Aborting...
```

**Comment by jrouleau** [comment]
It appear that the issue it stemming from here:
https://github.com/archlinux/devtools/blob/d8d2e23247a1aab5e269ff0e388e378ec9d462eb/arch-nspawn.in#L68-L79

My local repositories have a `file://.../$repo/os/$arch` path and while `pacconf` is resolving it correctly, the `sed -r 's#(.*/ [^/]+/os/.+#\1$repo/os/$arch#')` on L70 is  changing it back to `$repo` and `$arch`. That creates an invalid path so it fails to bind

**Comment by AladW** [comment]
I'm not sure why all those lines are needed in the first place, maybe some clarification can be added here.

**Comment by anthraxx** [comment]
@jrouleau can you test the patch attached in #30
