### ISSUE TITLE
arch-nspawn and a CacheDir configuration issue

### ISSUE THREAD

**Issue by lightdot** [archlinux/devtools#31]
I'm using aurutils to manage AUR packages and when using it with a chroot (`aur sync -cu`), the `/var/lib/aurbuild/x86_64/root/etc/pacman.conf` gets populated with the following on two separate occasions, the three dots actually replacing many repetitions of the two paths:

````
[options]
CacheDir = /var/cache/pacman/pkg/ /var/cache/pacman/custom/ /var/cache/pacman/pkg/ /var/cache/pacman/custom/ /var/cache/pacman/pkg/ /var/cache/pacman/custom/ /var/cache/pacman/pkg/ /var/cache/pacman/custom/ ...
````

It seems that each run appends additional instances of the two paths so the first fresh run goes through, later ones fail due to the excessive CacheDir repetitions.

I'm using a `/etc/pacman.d/custom` with:

````
[options]
CacheDir = /var/cache/pacman/pkg
CacheDir = /var/cache/pacman/custom

[custom]
SigLevel = Optional TrustAll
Server = file:///var/cache/pacman/custom
````
The `/etc/pacman.d/custom` is included at the end of the `/etc/pacman.conf` and the PKGDEST points to `/var/cache/pacman/custom`.

This has been happening for a short while now...

**Comment by Foxboron** [comment]
Check if master solves the issue.

https://github.com/archlinux/devtools/commit/00671765296ad598f392df7a542dbfca48a6e7b7

https://github.com/archlinux/devtools/commit/f43a86ee8a3a3bfbdc32c2d70516d945afcd8515

Should have solved the issue.

**Comment by anthraxx** [comment]
@lightdot does the thumbs up mean its fixed? if so, please state and close the issue

**Comment by lightdot** [comment]
Sorry for not returning to this sooner.

I have now tested the 20191130, 20191212 and the 20191227 releases and the issue is still present.

If it's of any assistance, find attached /var/lib/aurbuild/x86_64/root/etc/pacman.conf files, the initial one, then those generated after the first run and after the second run. It continues in this manner on subsequent runs, adding more and more.

[pacman.conf.initial.txt](https://github.com/archlinux/devtools/files/4032420/pacman.conf.initial.txt)
[pacman.conf.1st-run.txt](https://github.com/archlinux/devtools/files/4032418/pacman.conf.1st-run.txt)
[pacman.conf.2nd-run.txt](https://github.com/archlinux/devtools/files/4032419/pacman.conf.2nd-run.txt)
