### ISSUE TITLE
makechrootpkg: use COMPRESS* variables from makepkg.conf

### ISSUE THREAD

**Issue by clawoflight** [archlinux/devtools#32]
Compression is the bottleneck for many of the packages I build.
I would like to enable multi-core compression or even better zstd, now that we support that.

Can we modify makechrootpkg to also use the COMPRESS* variables from makepkg.conf?

**Comment by anthraxx** [comment]
enabling multi core compression breaks reproducible builds so its not gonna be picket up from host makepkg configuration. If you want to solve that for your own packages, you can provide an own wrapper variant like aur-build and have an according makepkg.conf that suites your needs. However there won't be an official way to override COMPRESS as that would open the gates for non-reproducible packages of the official repo.

**Comment by clawoflight** [comment]
Okay, that makes sense. I assume that the same holds for PKGEXT then? (regarding zstd)
