### ISSUE TITLE
dotnet-core needs CAP_IPC_LOCK to build with nspawn

### ISSUE THREAD

**Issue by alucryd** [archlinux/devtools#35]
.NET CoreCLR needs mlock to run, building dotnet-core with nspawn currently involves passing `--capability=CAP_IPC_LOCK` to arch-nspawn in makechrootpkg.

Upstream bug report: https://github.com/dotnet/source-build/issues/285

**Comment by alucryd** [comment]
Actually building the runtime itself works now with 3.1. I'm still worried about a comment implying the fix only concerns portable builds though, I guess trying to package msbuild or powershell will clear this doubt.

**Comment by anthraxx** [comment]
msbuild seems to build just fine :thinking:

**Comment by alucryd** [comment]
Awesome, then this is a non issue :)
